version: "3.3"


services:

  mooder-dev-postgres:
    image: mymooder-api
    container_name: mymooder-api
    ports:
      - "8080:8080"
    # environment:
    #   - POSTGRES_PASSWORD=example
    networks:
      - mooder-dev


networks:
  mooder-dev:
    driver: bridge