set shell := ["bash", "-uc"]
set dotenv-load

project_frontend := "mymooder-frontend"
project_src := "src"
project_app := "app"
flags := env_var_or_default("JUST_FLAGS", "-eo pipefail")
thumbup := "\\U1F44D"
check := "\\U2705"
warn := "\\U26A0"
# NVM_DIR := "/root/.nvm"
nvm_dir := env_var_or_default("NVM_DIR", "$HOME/.nvm")
node_version := "20.10.0"

# React Native Environmental Variables
app_name:= env_var_or_default("APP_NAME", "mymooder")
node_env := env_var_or_default("NODE_ENV", "test")
eas_build_profile := env_var_or_default("EAS_BUILD_PROFILE", "preview") # test, development, adhoc
patch_package := "npx patch-package react-native-leaflet-view"


# Install Dependencies for the React Native Front End

# Start the React Native Front End
# install-frontend:
#     #!/usr/bin/env bash
#     set {{flags}}
#     # pushd ./{{project_frontend}}
#     just install-nvm

# Install nvm. 
ubuntu-install-nvm:
    #!/usr/bin/env bash
    set {{flags}}
    sudo apt install -y curl
    sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    export NVM_DIR="{{nvm_dir}} > "$NVM_DIR/.nvmrc"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" > "$NVM_DIR/.nvmrc"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  > "$NVM_DIR/.nvmrc"  # This loads nvm bash_completion
    
    source ~/.bashrc
    . "$NVM_DIR/nvm.sh" && nvm install {{node_version}}
    . "$NVM_DIR/nvm.sh" && nvm use v{{node_version}}
    . "$NVM_DIR/nvm.sh" && nvm alias default v{{node_version}}
    node --version > "$NVM_DIR/.nvmrc" 
    npm --version > "$NVM_DIR/.nvmrc" 

# Install nvm. 
macos-install-nvm:
    brew install curl apt-get
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    export NVM_DIR="$HOME/.nvm" > "{{nvm_dir}}/.nvmrc"
    [ -s "{{nvm_dir}}/nvm.sh" ] && \. "{{nvm_dir}}/nvm.sh" > "{{nvm_dir}}/.nvmrc"  # This loads nvm
    [ -s "{{nvm_dir}}/bash_completion" ] && \. "{{nvm_dir}}/bash_completion"  > "{{nvm_dir}}/.nvmrc"  # This loads nvm bash_completion
    
    source ~/.zshrc
    . {{nvm_dir}}/nvm.sh && nvm install {{node_version}}
    . {{nvm_dir}}/nvm.sh && nvm use v{{node_version}}
    . {{nvm_dir}}/nvm.sh && nvm alias default v{{node_version}}
    source ~/.zshrc

    node --version > {{nvm_dir}}/.nvmrc
    npm --version > {{nvm_dir}}/.nvmrc 


# Remove previous node_modules and reinstalls from package.json
START_WITH_CLEAN_NODE_MODULES_react-install-clean-cache:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    sudo npm cache clean --force

    rm -rf ./node_modules
    npm install

    # Apply patched location to leaflet.html
    {{patch_package}}

# If developing through cloud expo resources, install dependencies
# This also sets the name of the project to src
A_expo-setup-install:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    # Sign up for expo account
    curl https://expo.dev/signup

    # Create new project 
    # npx create-expo-app {{app_name}}
    #############################
    # Or Create React Native app
    # npx create-react-native-app {{app_name}}
    ##############################

    # Supports local dev builds with either XCode or Android Studio
    npm install --save expo-dev-client

    # Install expo/types for jsx
    npm install --save --global expo-cli

    # Plan to build with Cloud-based Expo tools
    # Install lates EAS cli
    # Installing with cloud building through Expo from https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical
    npm install --save --global eas-cli

    # Create the metro-config.js file to help with APP ROUTing
    npx expo customize metro.config.js

    # Login into Expo Application Service (EAS)
    eas login

    # Confirm you're logged in
    eas whoami

A1_remove_android_and_ios_previous_builds:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}
    rm -rf ./ios
    rm -rf ./android

A2_configure_and_build_both_platforms: C_expo-build-configure D_expo-local-pre-build

# Run ios app locally
B1_expo-local-run-ios:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    NODE_ENV={{node_env}} npx expo run:ios

# Run android app locally
B2_expo-local-run-android:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    NODE_ENV={{node_env}} npx expo run:android

# Run ios app locally
B3_expo-local-run-web:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    NODE_ENV={{node_env}} npx expo run:web --clear

# Start local app running for debugging on the website
B4_expo-start:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    NODE_ENV={{node_env}} npx expo start

# Configures build configurations and set environmental variables
C_expo-build-configure:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    # Create Expo build configuration
    eas build:configure

    # Enroll in the Apple Developer Program for a personal device 

# Create native Android or iOS directories for the local project - preparing to publish to Expo
D_expo-local-pre-build:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    npx expo prebuild

# Build App to Be Transfered to a Expo or Dockerfile for deployment through Apps Developer Program
E_expo-build:
    #!/usr/bin/env bash
    set {{flags}}
    pushd {{project_src}}

    # Install dependencies
    # npm install -g eas-cli

    # Login to the Expo account
    # eas login

    #### Android credentials ######
    # Get credentials for Android
    # eas credentials

    # Package up credentials for Android
    # eytool -export -rfc -alias 2ae1a6233d053ff97b0751c040ec5e8c -file certificate_for_google.pem -keystore @ksundeen__mymooder.jks
    #### /Android credentials ######

    # Configure the build environments
    eas build:configure

    # Pre-build the apps
    npx expo prebuild

    ##### iOS #########
    # Run the build with the iOS internal build and create the registration for it
    # This can be run separately to register each device to allow install
    # eas device:create 
    ## OR ## to generate the credentials for me
    eas build -p ios

    # To redesignate credentials for IOS use
    # eas build:resign
    ##### /iOS ##########

    # Create the build
    # eas build --platform ios --profile {{eas_build_profile}}

    eas build --platform android --profile {{eas_build_profile}}

    # eas build --platform all --profile {{eas_build_profile}}

    # Submit to Android & Apple store, but these need to be production profiles
    # eas submit --platform ios --profile {{eas_build_profile}}

# Install React Native Sample App
z_DO_NOT_USE_react-native-new_install:
    #!/usr/bin/env bash
    source ~/.bashrc
    set {{flags}}
    pushd {{project_src}}

    # Apply patched location to leaflet.html
    {{patch_package}}
    
    # Install additioanal package to include sqlite storage
    npm install --save react-native-sqlite-storage
    apt install gradles