version: "3.3"

services:

  mmymooder-frontend:
    image: mymooder-frontend
    container_name: mymooder-frontend
    ports:
      - 8080:8081
      # - "5432:5432"
    # environment:
    #   - POSTGRES_PASSWORD=example
    networks:
      - mymooder-dev

networks:
  mymooder-dev:
    driver: bridge