version: "3.3"


services:

  mmymooder-frontent:
    image: mmymooder-frontent
    container_name: mmymooder-frontent
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - mooder-dev



networks:
  mooder-dev:
    driver: bridge